platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpbackup
    path: go/src/github.com/greenplum-db/gpbackup
  - name: gpdb_src
  - name: compiled_bits_ubuntu16
outputs:
params:
  CONFIGURE_FLAGS: ""
  TRANSFER_DIR: compiled_bits_ubuntu16
  COMPILED_BITS_FILENAME: compiled_bits_ubuntu16.tar.gz
run:
  path: go/src/github.com/greenplum-db/gpbackup/ci/scripts/ubuntu_tests.bash
